services:
  - type: web
    name: ctool-full-terminal
    env: python
    region: oregon
    plan: starter
    buildCommand: rm -rf .venv && echo "Xóa .venv cũ"
    startCommand: ./setup-pyenv.sh && pip install -r requirements.txt && python server.py
    envVars:
      PYTHON_VERSION: 3.11.9
